const fs = require('fs-extra');
const path = require('path');
const { parseBindString } = require('../../libs/helpers');

module.exports = function(app) {
    let router = app.webserver.router;

    let publicPath = app.conf.relativePath(app.conf.get('webserver.public_dir'));

    router.get('kiwi.bnc_plugin', '/kiwibnc_plugin.html', async (ctx, next) => {
        ctx.body = await fs.readFile(
            path.join(__dirname, 'kiwibnc_plugin.html'),
            { encoding: 'utf8' },
        );
    });

    router.get('kiwi.config', '/static/config.json', async (ctx, next) => {
        let config = await fs.readFile(path.join(publicPath, 'static', 'config.json'));
        config = JSON.parse(config);
        config = {
            ...config,
            '## comment': 'Auto generated by KiwiBNC',
            kiwiServer: '',
            startupScreen: 'kiwibnc',
        };

        config.startupOptions = {
            ...config.startupOptions,
            port: '{{port}}',
            server: '{{hostname}}',
            direct_path: '/',
            tls: '{{tls}}',
            direct: true,
            channel: '',
            bouncer: true,
            remember_buffers: false,
            public_register : app.conf.get('webchat.public_register', false),
        };

        // Add our kiwi plugin to the config
        config.plugins = config.plugins || [];
        config.plugins.push({
            name: 'kiwibnc',
            url: router.url('kiwi.bnc_plugin', {}),
            basePath: ctx.basePath,
        });

        let extraConf = app.conf.get('webchat');
        for (let prop in extraConf) {
            config[prop] = extraConf[prop];
        }

        ctx.body = config;
    });

    // Auth for the per-account client-config API: decrypt the kiwibnc/clientconfig
    // ISUPPORT token (encrypted `userid=<id>`) and expose it as ctx.state.userId.
    async function clientAuth(ctx, next) {
        if (!ctx.headers['x-auth']) {
            ctx.response.status = 403;
            return;
        }

        let userId = null;
        try {
            let token = app.crypt.decrypt(ctx.headers['x-auth']) || '';
            let m = token.match(/^userid=(\d+)/);
            if (!m) {
                throw new Error('invalid token');
            }
            userId = parseInt(m[1], 10);
        } catch (err) {
            ctx.response.status = 403;
            return;
        }

        ctx.state.userId = userId;
        await next();
    }

    router.get('kiwi.clientconfig', '/api/clientconfig', clientAuth, async (ctx, next) => {
        let raw = await app.userDb.getUserSettings(ctx.state.userId);
        let settings = {};
        if (raw) {
            try {
                let parsed = JSON.parse(raw);
                if (parsed && typeof parsed === 'object' && !Array.isArray(parsed)) {
                    settings = parsed;
                }
            } catch (err) {
                // Stored value is corrupt; hand back an empty object rather than erroring
            }
        }
        ctx.body = { settings };
    });

    router.put('kiwi.clientconfig', '/api/clientconfig', clientAuth, async (ctx, next) => {
        let settings = ctx.request.body && ctx.request.body.settings;
        if (!settings || typeof settings !== 'object' || Array.isArray(settings)) {
            ctx.body = { error: 'invalid_settings' };
            return;
        }

        try {
            await app.userDb.setUserSettings(ctx.state.userId, JSON.stringify(settings));
        } catch (err) {
            ctx.body = { error: err.code || 'unknown_error' };
            return;
        }

        ctx.body = { error: false };
    });

    app.webserver.router.post('kiwi.config', '/api/register', async (ctx, next) => {
        if (!app.conf.get('webchat.public_register', false)) {
            ctx.body = {error: 'forbidden'};
            return;
        }

        let body = ctx.request.body;
        if (!body.username || !body.password) {
            ctx.body = {error: 'missing_params'};
            return;
        }

        if (await app.userDb.getUser(body.username)) {
            ctx.body = {error: 'username_in_use'};
            return;
        }

        let admin = false;

        // If this is the first user, make them an admin
        let usersExist = await app.db.factories.User.query().first();
        if (!usersExist) {
            admin = true;
        }

        try {
            let user = await app.userDb.addUser(body.username, body.password, admin);
        } catch (err) {
            if (err.message === 'Invalid username') {
                ctx.body = {error: 'invalid_username'};
            } else {
                ctx.body = {error: 'unknown_error'};
            }

            return;
        }

        ctx.body = {error: false};
    });
};
